pub mod compile;
pub mod control_flow;
pub mod function;
pub mod function_call;
pub mod learned_value;
pub mod loops;
pub mod math;
pub mod struct_declaration;
pub mod variable_assignment;
pub mod variable_declaration;

pub use compile::{ CompilationContext, compile_pair, compile_pairs, };
pub use control_flow::if_statement::IfStatement;
pub use control_flow::return_statement::Return;
pub use control_flow::void_return_statement::VoidReturn;
pub use learned_value::LearnedValue;
pub use loops::for_loop::ForLoop;
pub use function::Function;
pub use function_call::FunctionCall;
pub use math::Math;
pub use struct_declaration::StructDeclaration;
pub use variable_assignment::VariableAssignment;
pub use variable_declaration::VariableDeclaration;
pub use loops::while_loop::WhileLoop;
