[package]
name = "ai-dsl2-code-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ai-dsl2-compiler = { path = "../compiler" }
pest = "2.4.0"
pest_derive = "2.4.0"
